version: '3.7'

services:
    database:
        container_name: postgres
        image: postgres:latest
        networks:
            - webnet
        environment:
            POSTGRES_DB: ${DB_NAME}
            POSTGRES_PASSWORD: ${DB_PWD}
        ports:
            - ${DB_PORT}:${DB_PORT}
        expose:
            - ${DB_PORT}
networks:
    webnet: